reports:
  exclude_contracts:
    - Ownable
    - Context
    - ERC20
    - SafeERC20
    - Address
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.2.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.2.0'
    optimizer:
      enabled: true
      runs: 200
networks:
  default: mainnet-fork
